# .github/workflows/android_build.yml
name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        androidExportType: [androidPackage, androidAppBundle] # apk, aab

    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        if: ${{ matrix.androidExportType == 'androidAppBundle' || matrix.androidExportType == 'androidPackage' }}

      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ matrix.androidExportType }}-unity-${{ vars.UNITY_VERSION || '6000.3.5f1' }}
          restore-keys: |
            Library-Android-${{ matrix.androidExportType }}-
            Library-Android-
            Library-

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
           UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
           UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
           UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ${{ vars.UNITY_PROJECT_PATH || '.' }}
          unityVersion: ${{ vars.UNITY_VERSION || '6000.3.5f1' }}
          targetPlatform: Android

          androidExportType: ${{ matrix.androidExportType }}

          # 서명(필요 시)
          androidKeystoreName: keystore.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

          # 버전(원하면 사용)
          # androidVersionCode: ${{ github.run_number }}
          # version: 1.0.${{ github.run_number }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-${{ matrix.androidExportType }}-build-${{ github.run_number }}
          path: build/Android
          retention-days: 14
