name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        projectPath: [ '.' ]
        unityVersion: [ 6000.3.5f1 ]
        androidExportType: [ androidPackage, androidAppBundle ] # apk, aab

    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1

      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      # Unity Library 캐시 (프로젝트 경로 기준)
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ runner.os }}-${{ matrix.projectPath }}-Android-${{ matrix.unityVersion }}-${{ matrix.androidExportType }}
          restore-keys: |
            Library-${{ runner.os }}-${{ matrix.projectPath }}-Android-${{ matrix.unityVersion }}-
            Library-${{ runner.os }}-${{ matrix.projectPath }}-Android-
            Library-${{ runner.os }}-${{ matrix.projectPath }}-
            Library-${{ runner.os }}-

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          # 가능하면 이 방식이 더 안정적
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: Android
          androidExportType: ${{ matrix.androidExportType }}

          # 서명(필요 시)
          androidKeystoreName: keystore.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}

          # 버전(원하면 사용)
          # androidVersionCode: ${{ github.run_number }}
          # version: 1.0.${{ github.run_number }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-${{ matrix.androidExportType }}-Unity-${{ matrix.unityVersion }}-Run-${{ github.run_number }}
          path: build/Android
          retention-days: 14
